name: 'Docker APK Version'
description: 'Check package version in an alpine docker image'
inputs:
  image:
    description: 'docker image (and tag) to use'
    required: true
    default: ghcr.io/fopina/postfix-relay:latest
  package:
    description: 'apk package to query'
    required: true
    default: postfix
  install:
    description: 'apk add package first to check latest version'
    required: false
outputs:
  version:
    description: "Version"
    value: ${{ steps.version-output.outputs.version }}
runs:
  using: "composite"
  steps:
    - name: Get used version
      id: version-output
      if: inputs.install != 'true'
      shell: bash
      run: |
          TAG=$(docker run --rm \
                            --entrypoint "" \
                            ${{ inputs.image }} \
                            apk version ${{ inputs.package }} | grep ^${{ inputs.package }} | cut -d '=' -f2 | tr -d ' ')
          echo version=${TAG} >> $GITHUB_OUTPUT
          echo ${{ inputs.image }} installed version of ${{ inputs.package }} is ${TAG}
    - name: Get latest version
      id: version-output
      if: inputs.install == 'true'
      shell: bash
      run: |
          TAG=$(docker run --rm \
                            --entrypoint "" \
                            ${{ inputs.image }} \
                            sh -c "apk add ${{ inputs.package }} && apk version ${{ inputs.package }}" | grep ^${{ inputs.package }} | tail -n1 | cut -d '=' -f2 | tr -d ' ')
          echo version=${TAG} >> $GITHUB_OUTPUT
          echo ${{ inputs.image }} latest version of ${{ inputs.package }} is ${TAG}
